### ISSUE TITLE
Doesn't decode DMR or POCSAG

### ISSUE THREAD

**Issue by gymnae** [0xAF/openwebrx-softmbe-docker#1]
Hi there,
great initiative. I tried the image you published and docker hub and the digi modes are available to chose from, but there's no decoding taking place. 
I tried your shell script locally in a stable container built from the stable source image and the shell script failed to install all required packages.

**Comment by 0xAF** [comment]
I wonder why the decoding is not working for you. It works for me and one guy I know, who is running this image.

The stable version of OWR is based on older debian and there are problems with some libs.
I decided to stick to the current/latest version, since it will soon be stable (I hope) and because I was too lazy to investigate the issues with the codec server on the older debian.

Can you make some more tests. Perhaps on another box and check the docker container logs for something that hints the problem?

**Comment by gymnae** [comment]
I now switched to your docker image and same thing. 
I see no telling error messages in the logs:
```
$ docker logs -f openwebrx
2021-10-17 20:50:11,343 - owrx.source - DEBUG - activating profile 7ff9a2e0-7ae9-4720-9052-d068d4f567c8 for 23be32e3-43c6-4eda-8bca-1a9e660ab834
Hello, I'm the codecserver.
now scanning for modules...
registering new driver: "ambe3k"
registering new driver: "softmbe"
loading devices from configuration...
registering new device for codecs: ambe,
auto-detecing devices...
scanning for "ambe3k" devices...
scanning for "softmbe" devices...
device scan complete.
check for codec: ambe
client requests codec ambe
renegotiating: direction: decode; Activating AMBE_3600x2450 decoder.
[...]
2021-10-17 22:22:43,379 - owrx.source - DEBUG - activating profile 7ff9a2e0-7ae9-4720-9052-d068d4f567c8 for 23be32e3-43c6-4eda-8bca-1a9e660ab834
2021-10-17 22:22:52,660 - owrx.service.schedule - DEBUG - no active schedule, scheduler standing by for external events.
	client requests codec ambe
renegotiating: direction: decode; Activating AMBE_3600x2450 decoder.
```

**Comment by 0xAF** [comment]
Hmm, seems ok to me... Are you sure it's not working as you expected it? How do you test it?

**Comment by gymnae** [comment]
I tried to listen to DMR - there was no voice coming from the speaker and no decoding of callsigns. Then I tried to decode POCSAG messages coming from a local relay. No decode.
Both of these worked fine with earlier versions of openwebrx

**Comment by 0xAF** [comment]
Hm, sorry, I have no idea... 
I'm using it for DMR and YSF and it "works for me" (TM) :)
I will leave this issue open, in case you find something which helps you to resolve the problem.
I suggest you to try on another PC and see if it works there, perhaps this will lead you to the cause of the problem.
I'm new to the whole HAM stuff (just got licensed a month ago) and I just wanted to have an SDR to test my radio emissions, and obviously the digital modes too.
You can share your experience here and I will try to dig around with you, but so far I do not see how can I help.

**Comment by 0xAF** [comment]
BTW, I just tested it on some random simplex freqency and the DMR is not decoded... but when I test it on a local DMR repeater it works as expected.
So perhaps my radio settings for the DMR simplex are not OK...
But just in case, can you try to listen to a DMR repeater and see if it works there?

**Comment by gymnae** [comment]
Interesting idea. I changed the gain and attempted with a different DMR signal, not from my hotspot. Now it works. The gain helped POCSAG and it just has problems decoding my hotspot, even though it's antenna is very close.
